version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysql5
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tmddud333
      MYSQL_USER: tmddud333
      MYSQL_PASSWORD: abd123
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"
    ports:
      - 33060:3306
